spring:
  application:
    name: usermanagement2
  datasource:
    url: jdbc:h2:file:./db
    driverClassName: org.h2.Driver
    username: sa
    password:

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    url: jdbc:h2:file:./db
    user: sa
    password:
    drop-first: false
  jpa:
    hibernate:
      naming:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
  test:
    database:
      replace: none
  flowable:
    databaseSchemaUpdate: none
  h2:
    console:
      enabled: true
server:
  port: 8080
logging:
  group:
    tomcat: "org.apache.catalina,org.apache.coyote,org.apache.tomcat"
  level:
    tomcat: "trace"
